# Generated by Django 3.2.9 on 2021-11-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('necessary', 'Necessary')], default='necessary', max_length=56),
        ),
    ]
