# Generated by Django 3.2.9 on 2021-11-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_time', '0002_activity_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='finished',
        ),
        migrations.CreateModel(
            name='ActedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.DateTimeField(verbose_name='date finished')),
                ('activity', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='track_time.activity')),
            ],
        ),
    ]
