version: "3"

services:
  track_webapp:
    build: .
    command: /app/entry_point.sh
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"
    depends_on:
      - track_db

  track_db:
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    restart: always
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data